spring:
  application.name: scheduler
  datasource:
    url: jdbc:h2:mem:bank
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
